name: Awesome-Lint

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x (LTS)
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and lint/test
      run: |
        npm ci
        npm run build --if-present
        npm test
